@base = http://localhost:8080

### Admin login -> adminJwt
# @name adminLogin
POST {{base}}/api/v1/admin/auth/login
Content-Type: application/json

{
  "email": "admin@bankify.local",
  "password": "admin123"
}

> {%
    client.global.set("adminJwt", response.body.token);
%}







