### =========================
### Setup
### =========================


@base = http://localhost:8080
@adminJwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NWFhOGJhMC00ZWNkLTRmNDktYTIyOC1jYjhiNzIzZTRmMjIiLCJ0eXAiOiJVU0VSIiwiZW1haWwiOiJhZG1pbkBiYW5raWZ5LmxvY2FsIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcwMzY1MjY2LCJleHAiOjE3NzAzNjg4NjZ9.-3BtezGApCuLnQ6-rclYU_mJNb90xqeB-MnEAWnS7v4
@partnerJwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MGYwOTEyNy1kZDM0LTQ2NzctOTc4YS1iZjNhYWM4NjI5MmUiLCJ0eXAiOiJQQVJUTkVSX1BPUlRBTCIsImVtYWlsIjoiZGV2QGNsaWVudDEyMy5jb20iLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE3NzAzNjQxNzUsImV4cCI6MTc3MDM2Nzc3NX0.IUxRMphSZjqcfMgXcVWwq7BWd8-IJknW6Hp6nr9Dw5U
@partnerAPI = aad41b355dcb5e4be6bcb27f494d993727dcfd5cafe45054a3888d3742b03422
@NewApiKey = 8096a8c9c462d9c5e46fd6c72ca1c63b4e5aaec4888c990a195b19182585e7f1
### =========================
### 1) Partner Signup (public)
### =========================
# @name partnerSignup
POST {{base}}/api/partner/auth/signup
Content-Type: application/json

{
  "appName": "My Client App",
  "email": "dev@client123.com",
  "password": "Passw0rd!",
  "callbackUrl": "https://client.com/webhooks/bankify"
}

> {%
    client.global.set("clientAppId", response.body.clientAppId);
%}

### =========================
### 2) Partner Portal Login (public)
### =========================
# @name partnerLogin
POST {{base}}/api/partner/auth/login
Content-Type: application/json

{
  "email": "dev@client123.com",
  "password": "Passw0rd!"
}

> {%
    client.global.set("portalJwt", response.body.token);
%}

### =========================
### 3) Portal Me (PARTNER_PORTAL JWT)
### =========================
GET {{base}}/api/partner/portal/me
Authorization: Bearer {{portalJwt}}

### =========================
### 4) Admin Login to get jwt
### =========================
### Admin Login
# @name adminLogin
POST {{base}}/auth/login
Content-Type: application/json

{
  "email": "admin@bankify.local",
  "password": "admin123"
}
> {%
    client.global.set("adminJwt", response.body.token);
%}

### =========================
### 4) Admin approve client account creatoin
### =========================
### Admin Login
@clientId = 3228e052-80ed-4bb4-9073-6b787b6bb609
# @name adminApproveClient
PATCH {{base}}/api/admin/clients/{{clientId}}/approve
Authorization: Bearer {{adminJwt}}

### 4) Admin Approve ClientApp (issues API key once)
### =========================
# @name adminApproveClient
PATCH {{base}}/api/admin/clients/{{clientId}}/approve
Authorization: Bearer {{adminJwt}}

> {%
    client.global.set("apiKey1", response.body.apiKey);
%}

### =========================
### 5) Partner API call with API key (server-to-server)
### =========================
GET {{base}}/api/partner/me/balance
X-API-Key: {{partnerAPI}}

### =========================
### 6) Partner requests key rotation (portal JWT)
### =========================
# @name rotateRequest
POST {{base}}/api/partner/portal/keys/rotate-request
Authorization: Bearer {{portalJwt}}
Content-Type: application/json

{
  "reason": "suspected leak"
}

> {%
    client.global.set("rotationRequestId", response.body.requestId);
%}

### =========================
### 7) Partner lists rotation requests (portal JWT)
### =========================
GET {{base}}/api/partner/portal/keys/rotation-requests
Authorization: Bearer {{portalJwt}}




### =========================
### 8) Admin approves rotation request (new API key once)
### =========================
# @name adminApproveRotation
PATCH {{base}}/api/admin/{{rotationRequestId}}/approve
Authorization: Bearer {{adminJwt}}

> {%
    client.global.set("apiKey2", response.body.apiKey);
%}

### =========================
### 9) Old key should FAIL
### =========================
GET {{base}}/api/partner/me/balance
X-API-Key: {{NewApiKey}}

### =========================
### 10) New key should WORK
### =========================
GET {{base}}/api/partner/me/balance
X-API-Key: {{NewApiKey}}
