name: Deploy Bankify to EC2 (Docker Hub)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO: ${{ secrets.DOCKERHUB_REPO }}
          SHA_TAG: ${{ github.sha }}
        run: |
          docker build -t $USERNAME/$REPO:$SHA_TAG .
          docker tag $USERNAME/$REPO:$SHA_TAG $USERNAME/$REPO:v1
          docker push $USERNAME/$REPO:$SHA_TAG
          docker push $USERNAME/$REPO:v1

      - name: Deploy on EC2 via SSH
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}

        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

          # Ensure folder exists on EC2
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "mkdir -p ~/bankify"



          # Pull latest + restart
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "bash -lc '
            cd ~/bankify
            docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:v1
            docker compose up -d
            docker image prune -af || true
          '"
